### ISSUE TITLE
Failed to build cuda-colorspace v0.1.0 and ssimulacra2-cuda v0.1.0 on Linux

### ISSUE THREAD

**Issue by onek24** [Gui-Yom/video-hw-rs#11]
Installed cuda 12.6.3-1 and Video Codec SDK 12.2 headers and also added the environmental variables. 
Setup rustup nightly with components. 
Cargo build fails with the following error: 
```
   Compiling nvptx-builder v0.1.0 (/home/*/Transcoding/turbo-metrics/crates/nvptx-builder)
   Compiling cuda-colorspace v0.1.0 (/home/*/Transcoding/turbo-metrics/crates/cuda-colorspace)
   Compiling ssimulacra2-cuda v0.1.0 (/home/*/Transcoding/turbo-metrics/crates/ssimulacra2-cuda)
error: failed to run custom build command for `cuda-colorspace v0.1.0 (/home/*/Transcoding/turbo-metrics/crates/cuda-colorspace)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/*/Transcoding/turbo-metrics/target/release/build/cuda-colorspace-8da6bb6fb2d843cf/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/*/Transcoding/turbo-metrics/crates/cuda-colorspace-kernel/Cargo.toml
  cargo:rerun-if-changed=/home/*/Transcoding/turbo-metrics/crates/cuda-colorspace-kernel/src
  cargo:rerun-if-changed=/home/*/Transcoding/turbo-metrics/crates/cuda-colorspace-kernel/build.rs

  --- stderr
      Blocking waiting for file lock on package cache
      Blocking waiting for file lock on package cache
  warning: unused import: `crate::panic::*`
    --> crates/nvptx-std/src/lib.rs:15:13
     |
  15 |     pub use crate::panic::*;
     |             ^^^^^^^^^^^^^^^
     |
     = note: `#[warn(unused_imports)]` on by default

  warning: unused variable: `p`
     --> crates/nvptx-std/src/math.rs:112:24
      |
  112 |     fn powf_fast(self, p: Self) -> Self {
      |                        ^ help: if this is intentional, prefix it with an underscore: `_p`
      |
      = note: `#[warn(unused_variables)]` on by default

  warning: `nvptx-std` (lib) generated 2 warnings (run `cargo fix --lib -p nvptx-std` to apply 1 suggestion)
  warning: struct `Full` is never constructed
    --> crates/cuda-colorspace-kernel/src/lib.rs:73:8
     |
  73 | struct Full;
     |        ^^^^
     |
     = note: `#[warn(dead_code)]` on by default

  warning: struct `Special` is never constructed
     --> crates/cuda-colorspace-kernel/src/lib.rs:133:8
      |
  133 | struct Special;
      |        ^^^^^^^

  warning: struct `Passtrough` is never constructed
     --> crates/cuda-colorspace-kernel/src/lib.rs:176:8
      |
  176 | struct Passtrough;
      |        ^^^^^^^^^^

  warning: associated items `from`, `dot`, and `cross` are never used
    --> crates/cuda-colorspace-kernel/src/const_algebra.rs:14:18
     |
  9  | impl Vec2 {
     | --------- associated items in this implementation
  ...
  14 |     pub const fn from(arr: [f32; 2]) -> Self {
     |                  ^^^^
  ...
  21 |     pub const fn dot(self, other: Self) -> f32 {
     |                  ^^^
  ...
  25 |     pub const fn cross(self, other: Self) -> f32 {
     |                  ^^^^^

  warning: `cuda-colorspace-kernel` (lib) generated 4 warnings
      Finished `release-nvptx` profile [optimized] target(s) in 0.04s
  thread 'main' panicked at crates/nvptx-builder/src/lib.rs:81:9:
  ptxas validation failed
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/c26db435bf8aee2efc397aab50f3a21eb351d6e5/library/std/src/panicking.rs:681:5
     1: core::panicking::panic_fmt
               at /rustc/c26db435bf8aee2efc397aab50f3a21eb351d6e5/library/core/src/panicking.rs:75:14
     2: nvptx_builder::copy_file
     3: nvptx_builder::build_ptx_crate
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `ssimulacra2-cuda v0.1.0 (/home/*/Transcoding/turbo-metrics/crates/ssimulacra2-cuda)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/*/Transcoding/turbo-metrics/target/release/build/ssimulacra2-cuda-2e27d8ed385c2f11/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/home/*/Transcoding/turbo-metrics/crates/ssimulacra2-cuda-kernel/Cargo.toml
  cargo:rerun-if-changed=/home/*/Transcoding/turbo-metrics/crates/ssimulacra2-cuda-kernel/src
  cargo:rerun-if-changed=/home/*/Transcoding/turbo-metrics/crates/ssimulacra2-cuda-kernel/build.rs

  --- stderr
      Blocking waiting for file lock on package cache
      Blocking waiting for file lock on package cache
      Blocking waiting for file lock on build directory
  warning: unused import: `crate::panic::*`
    --> crates/nvptx-std/src/lib.rs:15:13
     |
  15 |     pub use crate::panic::*;
     |             ^^^^^^^^^^^^^^^
     |
     = note: `#[warn(unused_imports)]` on by default

  warning: unused variable: `p`
     --> crates/nvptx-std/src/math.rs:112:24
      |
  112 |     fn powf_fast(self, p: Self) -> Self {
      |                        ^ help: if this is intentional, prefix it with an underscore: `_p`
      |
      = note: `#[warn(unused_variables)]` on by default

  warning: `nvptx-std` (lib) generated 2 warnings (run `cargo fix --lib -p nvptx-std` to apply 1 suggestion)
  warning: the feature `core_intrinsics` is internal to the compiler or standard library
   --> crates/ssimulacra2-cuda-kernel/src/lib.rs:6:12
    |
  6 | #![feature(core_intrinsics)]
    |            ^^^^^^^^^^^^^^^
    |
    = note: using it is strongly discouraged
    = note: `#[warn(internal_features)]` on by default

  warning: unused variable: `dst_w`
    --> crates/ssimulacra2-cuda-kernel/src/downscale.rs:44:5
     |
  44 |     dst_w: usize,
     |     ^^^^^ help: if this is intentional, prefix it with an underscore: `_dst_w`
     |
     = note: `#[warn(unused_variables)]` on by default

  warning: unused variable: `dst_h`
    --> crates/ssimulacra2-cuda-kernel/src/downscale.rs:45:5
     |
  45 |     dst_h: usize,
     |     ^^^^^ help: if this is intentional, prefix it with an underscore: `_dst_h`

  warning: constant `VERT_MUL_IN_1` is never used
   --> /home/*/Transcoding/turbo-metrics/target/nvptx64-nvidia-cuda/release-nvptx/build/ssimulacra2-cuda-kernel-71a474a7ce972685/out/recursive_gaussian.rs:2:11
    |
  2 | pub const VERT_MUL_IN_1: f32 = 0.055295236_f32;
    |           ^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

  warning: constant `VERT_MUL_IN_3` is never used
   --> /home/*/Transcoding/turbo-metrics/target/nvptx64-nvidia-cuda/release-nvptx/build/ssimulacra2-cuda-kernel-71a474a7ce972685/out/recursive_gaussian.rs:3:11
    |
  3 | pub const VERT_MUL_IN_3: f32 = -0.058836687_f32;
    |           ^^^^^^^^^^^^^

  warning: constant `VERT_MUL_IN_5` is never used
   --> /home/*/Transcoding/turbo-metrics/target/nvptx64-nvidia-cuda/release-nvptx/build/ssimulacra2-cuda-kernel-71a474a7ce972685/out/recursive_gaussian.rs:4:11
    |
  4 | pub const VERT_MUL_IN_5: f32 = 0.012955819_f32;
    |           ^^^^^^^^^^^^^

  warning: constant `VERT_MUL_PREV_1` is never used
   --> /home/*/Transcoding/turbo-metrics/target/nvptx64-nvidia-cuda/release-nvptx/build/ssimulacra2-cuda-kernel-71a474a7ce972685/out/recursive_gaussian.rs:5:11
    |
  5 | pub const VERT_MUL_PREV_1: f32 = -1.9021131_f32;
    |           ^^^^^^^^^^^^^^^

  warning: constant `VERT_MUL_PREV_3` is never used
   --> /home/*/Transcoding/turbo-metrics/target/nvptx64-nvidia-cuda/release-nvptx/build/ssimulacra2-cuda-kernel-71a474a7ce972685/out/recursive_gaussian.rs:6:11
    |
  6 | pub const VERT_MUL_PREV_3: f32 = -1.1755705_f32;
    |           ^^^^^^^^^^^^^^^

  warning: constant `VERT_MUL_PREV_5` is never used
   --> /home/*/Transcoding/turbo-metrics/target/nvptx64-nvidia-cuda/release-nvptx/build/ssimulacra2-cuda-kernel-71a474a7ce972685/out/recursive_gaussian.rs:7:11
    |
  7 | pub const VERT_MUL_PREV_5: f32 = -0.00000000000000012246469_f32;
    |           ^^^^^^^^^^^^^^^

  warning: constant `SRGB_ALPHA` is never used
   --> crates/ssimulacra2-cuda-kernel/src/srgb.rs:4:7
    |
  4 | const SRGB_ALPHA: f32 = 1.055_010_7;
    |       ^^^^^^^^^^

  warning: constant `SRGB_BETA` is never used
   --> crates/ssimulacra2-cuda-kernel/src/srgb.rs:5:7
    |
  5 | const SRGB_BETA: f32 = 0.003_041_282_5;
    |       ^^^^^^^^^

  warning: function `srgb_eotf` is never used
   --> crates/ssimulacra2-cuda-kernel/src/srgb.rs:9:11
    |
  9 | unsafe fn srgb_eotf(x: f32) -> f32 {
    |           ^^^^^^^^^

  warning: constant `INVERSE_OPSIN_ABSORBANCE_MATRIX` is never used
    --> crates/ssimulacra2-cuda-kernel/src/xyb.rs:25:7
     |
  25 | const INVERSE_OPSIN_ABSORBANCE_MATRIX: [f32; 9] = [
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  warning: constant `NEG_OPSIN_ABSORBANCE_BIAS` is never used
    --> crates/ssimulacra2-cuda-kernel/src/xyb.rs:36:7
     |
  36 | const NEG_OPSIN_ABSORBANCE_BIAS: [f32; 3] = [-K_B0, -K_B1, -K_B2];
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^

  warning: `ssimulacra2-cuda-kernel` (lib) generated 14 warnings
      Finished `release-nvptx` profile [optimized] target(s) in 0.04s
  thread 'main' panicked at crates/nvptx-builder/src/lib.rs:81:9:
  ptxas validation failed
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/c26db435bf8aee2efc397aab50f3a21eb351d6e5/library/std/src/panicking.rs:681:5
     1: core::panicking::panic_fmt
               at /rustc/c26db435bf8aee2efc397aab50f3a21eb351d6e5/library/core/src/panicking.rs:75:14
     2: nvptx_builder::copy_file
     3: nvptx_builder::build_ptx_crate
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by onek24** [comment]
Weirdly enough a system restart fixed this issue... Can be closed i assume
